exclude = [
    ".vscode",
    ".mypy_cache",
    "migrations"
]

line-length = 81
indent-width = 4

[lint]
select = ["E", "W", "F", "I", "C4"]
ignore = ["F811", "F821"]

fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"

[lint.pydocstyle]
convention = "google"
